### ISSUE TITLE
CSS class collisions

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#28]
The CSS classes that you used, especially for the popup collide with almost everything in the frontend.

It's ok to use the CSS classes that you use, but make sure they are **always** used in a relative manner to your plugin.

Things like `$(".main-modal, #modal-background").toggleClass("active");` toggle the active class on all elements with the respective classes/ids on the **entire site**, not just four your map instance.

Also keep in mind, that the map could be used multiple times on one page. So a call to `$('devs')` selectes all devs on the entire page.

**So, make sure that all your selectors are used in a relative way. This goes for JS and CSS the same.**

**Comment by brianstanley** [comment]
OK I fixed #29 now I making that the ids of the dotteds patterns  can be setted by parameters as well.  Now I have a question with the css. How you say in the css you have things like .main-modal { ....} and that collide with the frontend, but if I set the parameters for classes  by JS is there a possibility to inject to the css right? with vars in sass or something like that? because then it's not a problem I think if we just  override the css classes automatically, because if it's not possible to override the css then the functionality of set the classes by JS is not useful
